### ISSUE TITLE
Clads is giving the opposite tip rates 

### ISSUE THREAD

**Issue by burbrink** [hmorlon/PANDA.jl#17]
Hello,

I have used Clads to estimate tip rates. It is giving the opposite pattern when compared to other metrics like DR (equal splits measure of Jetz et al. 2012). It certainly has to be some issue with Clads; the longest branches have the highest rates of speciation.  I have run this four times with different thinnings and the tip rates among multiple Clads runs are correlated (>0.89) and the Gelman is 1.01.

Any thoughts?

I am attaching a graph showing the correlation between clads and DR, a tree showing estimates of both rates, and the actual tree used to run DR in R and Clads in Julia. 

Any help would be much appreciated. 

Frank

[DR_Clads_rates.pdf](https://github.com/hmorlon/PANDA.jl/files/8572753/DR_Clads_rates.pdf)

[RatesCompared.pdf](https://github.com/hmorlon/PANDA.jl/files/8572755/RatesCompared.pdf)

[PL_red.txt](https://github.com/hmorlon/PANDA.jl/files/8572759/PL_red.txt)

**Comment by hmorlon** [comment]
Hello Frank, sorry for the late reply. What are the hyperparameters you found when fitting ClaDS? Which version of it (i.e., which hypothesis on extinction etc?). This is surprising, previous comparisons have found rather high correlations. This could be due to extiction (DR does not account for exctinction). Best Hélène
